### ISSUE TITLE
Should just install for current user (messing with system python won't work on OSX)

### ISSUE THREAD

**Issue by mikemaccana** [rdegges/stormpath-export#2]
Just:

```
pip install --user stormpath-export
```

Trying to install it globally tries to update shutil which messes with System Integrity Protection on OS X:

```
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-xnyHEq-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

Disabling System Integrity Protection is bad. Just install it per-user.

**Comment by rdegges** [comment]
This is actually totally dependent on how you have python installed. You should always install python packages into a virtualenv (preferably), or second-best at the user level. But -- this behavior should be the default behavior of pip unless it's installed in a non-standard way.

With that said, I'm not going to merge this as I think this is really dependent on the particular user who is installing, sorry!
